using System.Security.Cryptography;
using JiranisokoTech.Application.Abstractions;
using JiranisokoTech.Application.Authorization;
using JiranisokoTech.Domain.Api;

namespace JiranisokoTech.Application.Api;

public interface IApiKeyRepository
{
    Task<ApiKey?> FindAsync(Guid id, CancellationToken cancellationToken = default);

    Task<ApiKey?> ByHashAsync(string hash, CancellationToken cancellationToken = default);

    Task<List<ApiKey>> AllAsync(CancellationToken cancellationToken = default);

    void Add(ApiKey key);

    Task SaveAsync(CancellationToken cancellationToken = default);
}

/// <summary>A key, and the one time its secret is ever visible.</summary>
public sealed record IssuedKey(ApiKey Key, string Secret);

public sealed class ApiKeyService(IApiKeyRepository keys, IClock clock)
{
    public async Task<IssuedKey> IssueAsync(
        string name,
        IReadOnlyList<string> scopes,
        Guid? createdById,
        CancellationToken cancellationToken = default)
    {
        foreach (var scope in scopes)
        {
            if (!Permissions.All.Contains(scope))
            {
                // A scope that is not a permission would be silently ignored by
                // every check, producing a key that looks more capable than it
                // is. Refused rather than dropped.
                throw new ArgumentException(
                    $"\"{scope}\" is not a permission this system has.", nameof(scopes));
            }
        }

        var secret = NewSecret();

        var key = ApiKey.Issue(
            name,
            Fingerprint(secret),
            secret[^4..],
            scopes,
            createdById,
            clock.Now);

        keys.Add(key);
        await keys.SaveAsync(cancellationToken);

        return new IssuedKey(key, secret);
    }

    /// <summary>
    /// The key a secret belongs to, or nothing.
    /// </summary>
    /// <remarks>
    /// Looked up by the hash rather than by scanning and comparing, so this is
    /// one indexed read whatever the number of keys. Revoked keys are found and
    /// then refused by the caller, rather than filtered out here, so that using
    /// a revoked key can be told apart from using one that never existed.
    /// </remarks>
    public Task<ApiKey?> ResolveAsync(string secret, CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(secret) || !secret.StartsWith(ApiKey.SecretPrefix, StringComparison.Ordinal))
        {
            return Task.FromResult<ApiKey?>(null);
        }

        return keys.ByHashAsync(Fingerprint(secret), cancellationToken);
    }

    public async Task NoteUseAsync(ApiKey key, CancellationToken cancellationToken = default)
    {
        if (key.UsedOn(clock.Today))
        {
            await keys.SaveAsync(cancellationToken);
        }
    }

    public async Task RevokeAsync(
        Guid id, string reason, CancellationToken cancellationToken = default)
    {
        var key = await keys.FindAsync(id, cancellationToken)
            ?? throw new InvalidOperationException("There is no key with that identifier.");

        key.Revoke(reason, clock.Now);
        await keys.SaveAsync(cancellationToken);
    }

    public Task<List<ApiKey>> AllAsync(CancellationToken cancellationToken = default) =>
        keys.AllAsync(cancellationToken);

    /// <summary>
    /// Thirty-two random bytes, base64url, behind a recognisable prefix.
    /// </summary>
    /// <remarks>
    /// 256 bits from the operating system's generator. Not a readable phrase,
    /// not a GUID: a GUID is 122 bits with structure in it and is generated by
    /// something optimised for uniqueness rather than unguessability.
    /// </remarks>
    private static string NewSecret() =>
        ApiKey.SecretPrefix + Base64Url.Encode(RandomNumberGenerator.GetBytes(32));

    /// <summary>
    /// SHA-256 of the secret, hex.
    /// </summary>
    /// <remarks>
    /// A plain fast hash, deliberately, where a password would want a slow one.
    /// The reason a password needs bcrypt is that people choose passwords a
    /// dictionary contains; this is 256 bits of randomness, so there is no
    /// dictionary and no advantage to slowing an attacker who would need to
    /// exhaust the space anyway. And the cost is paid on every single API
    /// request: a deliberately slow hash there is a denial-of-service anybody
    /// can trigger by sending nonsense.
    /// </remarks>
    private static string Fingerprint(string secret) =>
        Convert.ToHexStringLower(SHA256.HashData(System.Text.Encoding.UTF8.GetBytes(secret)));
}

/// <summary>Base64 that survives being put in a header or a URL.</summary>
internal static class Base64Url
{
    public static string Encode(byte[] bytes) =>
        Convert.ToBase64String(bytes).TrimEnd('=').Replace('+', '-').Replace('/', '_');
}
