using JiranisokoTech.Application.Documents;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace JiranisokoTech.Infrastructure.Documents;

public sealed class DocumentStoreOptions
{
    public const string Section = "Documents";

    /// <summary>
    /// Where attachments are written. Relative paths are to the content root.
    /// </summary>
    /// <remarks>
    /// Deliberately not under wwwroot. Anything in wwwroot is handed to whoever
    /// guesses its address, and this folder holds client contracts and
    /// photographs of people's receipts. Every read goes through code that
    /// checks who is asking.
    ///
    /// In a container this wants a volume. Without one the files live inside
    /// the container and a deploy takes them with it — the same trap as the
    /// signing keys, with the difference that nobody notices until somebody
    /// opens an old invoice.
    /// </remarks>
    public string Directory { get; set; } = "documents";
}

/// <summary>Attachments on disk, under names this system chose.</summary>
public sealed class FileDocumentStore(
    IOptions<DocumentStoreOptions> options,
    ILogger<FileDocumentStore> logger) : IDocumentStore
{
    public async Task<string> SaveAsync(
        Stream contents, string originalName, CancellationToken cancellationToken = default)
    {
        var folder = Root();

        Directory.CreateDirectory(folder);

        /*
         * The extension comes from the allow-list, not from the name.
         * Path.GetExtension on a hostile name returns whatever followed the last
         * dot, and this is the one value from an upload that reaches the
         * filesystem.
         */
        var extension = Path.GetExtension(originalName);

        if (!Application.Documents.Documents.Extensions.Contains(extension))
        {
            throw new InvalidOperationException("That is not a document this system accepts.");
        }

        var stored = $"{Guid.CreateVersion7():N}{extension.ToLowerInvariant()}";

        await using var file = File.Create(Path.Combine(folder, stored));
        await contents.CopyToAsync(file, cancellationToken);

        logger.LogInformation("Stored an attachment as {Stored}.", stored);

        return stored;
    }

    public Task<Stream?> OpenAsync(
        string storedName, CancellationToken cancellationToken = default)
    {
        var path = Resolve(storedName);

        return Task.FromResult<Stream?>(
            path is not null && File.Exists(path) ? File.OpenRead(path) : null);
    }

    public Task DeleteAsync(string storedName, CancellationToken cancellationToken = default)
    {
        if (Resolve(storedName) is { } path && File.Exists(path))
        {
            File.Delete(path);
        }

        return Task.CompletedTask;
    }

    /// <summary>
    /// Turn a stored name into a path inside the folder, or nothing.
    /// </summary>
    /// <remarks>
    /// Names in the database were generated by this class, so this should never
    /// refuse anything. It checks all the same, because "it came from our own
    /// database" is exactly the assumption that turns one writable row into
    /// reading any file the process can see.
    /// </remarks>
    private string? Resolve(string storedName)
    {
        if (string.IsNullOrWhiteSpace(storedName)
            || storedName.Contains('/')
            || storedName.Contains('\\')
            || storedName.Contains(".."))
        {
            logger.LogWarning("Refused a stored document name: {Name}.", storedName);

            return null;
        }

        var folder = Path.GetFullPath(Root());
        var path = Path.GetFullPath(Path.Combine(folder, storedName));

        return path.StartsWith(folder, StringComparison.Ordinal) ? path : null;
    }

    private string Root()
    {
        var configured = options.Value.Directory;

        return Path.IsPathRooted(configured)
            ? configured
            : Path.Combine(AppContext.BaseDirectory, configured);
    }
}
